### ISSUE TITLE
Ошибка при пакетной загрузки

### ISSUE THREAD

**Issue by denny123** [rendrom/rosreestr2coord#11]
Команда:

             python rosreestr2coord.py -p /_r_to_c/ -o /_r_to_c/ -w -a -l list_kadnum.txt -P -e 1

Возвращает ошибку:

            Downloading completed. Uploaded tiles - 0
               - ok, from catalog, 0%
               60:01:0010253:157Run tiles download:
              100% 1/1Traceback (most recent call last):
               File "rosreestr2coord.py", line 4, in <module>
              main()
              File "/rosreestr2coord/scripts/console.py", line 128, in main
              _main()
                  File "/rosreestr2coord/scripts/console.py", line 94, in _main
                   output=output, file_name=file_name, with_attrs=with_attrs, delay=delay, 
              center_only=center_only, with_proxy=opt.proxy)
              File "/rosreestr2coord/scripts/batch.py", line 59, in batch_parser
             area = restore_area(restore, coord_out)
              File "/rosreestr2coord/scripts/parser.py", line 82, in restore_area
               area.restore(restore)
              File "/rosreestr2coord/scripts/parser.py", line 151, in restore
              self.get_geometry()
              File "/rosreestr2coord/scripts/parser.py", line 275, in get_geometry
               return self.parse_geometry_from_image()
             File "/rosreestr2coord/scripts/parser.py", line 288, in 
             parse_geometry_from_image
              image.download()
              File "/rosreestr2coord/scripts/merge_tiles.py", line 130, in download
              im = Image.open(os.path.join(self.tile_dir, os.listdir(self.tile_dir)[0]))
            File "/usr/local/lib/python2.7/dist-packages/Pillow-5.3.0.dev0-py2.7-linux-i686.egg/PIL/Image.py", line 2633, in open
              % (filename if filename else fp))
            IOError: cannot identify image file u'/rosreestr2coord/tmp/60_1_10253_157/0_0.png'

после удаления каталога tmp скрипт продвигается еще дальше и выдает аналогичную ошибку, приходится все время чистить tmp чтобы дойти до 100%......ужас

**Comment by denny123** [comment]
как я заметил на "битые картинки" натыкается, росреестр или скрипт не успевает сохранять данные....нз
