### ISSUE TITLE
Что за ошибки

### ISSUE THREAD

**Issue by TSA21432** [rendrom/rosreestr2coord#17]
Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\xxx>rosreestr2coord -t1 -w -l c:\cadastral_numbers_list.txt
Press Ctrl+C to exit
Catalog is required for batch mode!

C:\Users\xxx>rosreestr2coord -c 16:56:010115:1994 -t5 -w
Press Ctrl+C to exit
Traceback (most recent call last):
  File "C:\Python27\Scripts\rosreestr2coord-script.py", line 11, in <module>
    load_entry_point('rosreestr2coord==1.5.3', 'console_scripts', 'rosreestr2coo
rd')()
  File "C:\Python27\lib\site-packages\scripts\console.py", line 128, in main
    _main()
  File "C:\Python27\lib\site-packages\scripts\console.py", line 97, in _main
    get_by_code(code, path, area_type, catalog_path, with_attrs, epsilon, coord_
out, output, display, center_only, with_proxy=opt.proxy)
  File "C:\Python27\lib\site-packages\scripts\console.py", line 103, in get_by_c
ode
    coord_out=coord_out, center_only=center_only, with_proxy=with_proxy)
  File "C:\Python27\lib\site-packages\scripts\parser.py", line 126, in __init__
    self.catalog = Catalog(catalog)
  File "C:\Python27\lib\site-packages\scripts\catalog.py", line 16, in __init__
    self.open()
  File "C:\Python27\lib\site-packages\scripts\catalog.py", line 25, in open
    data = json.load(local_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 2449718 (char 2449717)

C:\Users\xxx>rosreestr2coord -c 16:56:010115:1994 -w
Press Ctrl+C to exit
Traceback (most recent call last):
  File "C:\Python27\Scripts\rosreestr2coord-script.py", line 11, in <module>
    load_entry_point('rosreestr2coord==1.5.3', 'console_scripts', 'rosreestr2coo
rd')()
  File "C:\Python27\lib\site-packages\scripts\console.py", line 128, in main
    _main()
  File "C:\Python27\lib\site-packages\scripts\console.py", line 97, in _main
    get_by_code(code, path, area_type, catalog_path, with_attrs, epsilon, coord_
out, output, display, center_only, with_proxy=opt.proxy)
  File "C:\Python27\lib\site-packages\scripts\console.py", line 103, in get_by_c
ode
    coord_out=coord_out, center_only=center_only, with_proxy=with_proxy)
  File "C:\Python27\lib\site-packages\scripts\parser.py", line 126, in __init__
    self.catalog = Catalog(catalog)
  File "C:\Python27\lib\site-packages\scripts\catalog.py", line 16, in __init__
    self.open()
  File "C:\Python27\lib\site-packages\scripts\catalog.py", line 25, in open
    data = json.load(local_file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 2449718 (char 2449717)

C:\Users\xxx>

**Comment by rendrom** [comment]
Ошибка каталога, который в новой версии он заменён на кэширование
