### ISSUE TITLE
Никак не возвращает никакие данные

### ISSUE THREAD

**Issue by denjob** [rendrom/rosreestr2coord#62]
`rosreestr2coord -c 60:22:0043901 -t 2 -P`

В росреестре такой квартал есть.
Может для этого квартала и нет никаких данных в API или это всетаки что-то блочит? Может у кого-то иной результат?

**Comment by lavAzza2** [comment]
При любом запросе

rosreestr2coord -t 2 -c 50:20:0100711:40 -P
Press Ctrl+C to exit
Area info loaded from file: E:\PyProject\r2c\tmp\50_20_100711_40\feature_info.json
Get tiles:
HTTP Error 403: Forbidden
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Azat\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Azat\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\merge_tiles.py", line 37, in task_wrapper
    result.put(target(*args))
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\merge_tiles.py", line 331, in fetch_tile
    img = self.get_image(x, y)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\merge_tiles.py", line 462, in get_image
    data = self._load_image_data(meta_url, cache_path)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\merge_tiles.py", line 475, in _load_image_data
    response = self.make_request(url)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\parser.py", line 196, in make_request
    response = make_request(url, self.with_proxy)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\utils.py", line 64, in make_request
    return make_request_with_proxy(url)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\utils.py", line 83, in make_request_with_proxy
    proxies = proxy_handling.load_proxies()
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\proxy_handling.py", line 79, in load_proxies
    update_proxies(path)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\proxy_handling.py", line 20, in update_proxies
    download_proxies(path)
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\proxy_handling.py", line 32, in download_proxies
    found = ip_adress_proxies()
  File "e:\pyproject\r2c\venv\lib\site-packages\rosreestr2coord\proxy_handling.py", line 54, in ip_adress_proxies
    found = [i.replace('</a>', '') + '\n' for i in re.findall(pattern, s)]
  File "C:\Users\Azat\AppData\Local\Programs\Python\Python37\lib\re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object


Completed, 0 tile received

**Comment by denjob** [comment]
На некоторых дает хотя бы один тайл, далее тыкаешь сам по несколько раз пока все тайлы не собирет и только тогда выдает результат. На некоторых ничего не дает даже если 50 раз запрос сделаешь с прокси или без. 403 вначале тоже выдавал, потом перестал. Наводит на мысль что росреестр что-то там мутит: блочит, закрывает, меняет и тп. Если у кого-то идет все стабильно хотелось бы услышать, но пока иное мнение....

**Comment by denjob** [comment]
Прога равняется на feature_info.json, если первый раз там ничего то она все время пишет что ничего не нашла. Далее удаляем этот файлик и заново пробуем, если возвращает инфу, то далее 50 раз тыкаем чтобы все тайлы скачала и тогда только результат. 403 возвращает у меня только через прокси(возможно не те прокси). Думаю тут можно в скриптах дописать, чтобы все делалось автоматом с проверкой и например доппараметром с количеством итераций проб, это сделает данный скрипт актуальным и более "автоматическим".

**Comment by rendrom** [comment]
Спасибо, что написали. Я сам скриптом не пользуюсь и не узнал бы про ошибку.
Был сбой загрузки списка адресов прокси-серверов. Сейчас поменял сервис и загрузка участков снова пошла.
![image](https://user-images.githubusercontent.com/1478481/177322197-8d17e9f2-8d48-4942-8dec-1053884277b8.png)

Прошу проверить у себя ещё и закрывать тикет.

По поводу предложений заведите, пожалуйста, другой репорт

**Comment by denjob** [comment]
Да, прокси робит без 403. Хотя этот репорт я не из-за этого заводил) Заведу новый тогда.
