### ISSUE TITLE
Ошибка при получении координат объекта ЗОУИТ

### ISSUE THREAD

**Issue by AlekseiGrigorev** [rendrom/rosreestr2coord#66]
Уважаемые коллеги, добрый день! Большое спасибо за удобный инструмент! К сожалению, при выполнении команды rosreestr2coord -t 10 -c 38:00-6.744 сообщение об ошибке:

(py356) C:\Users\lelik>rosreestr2coord -t 10 -c 38:00-6.744
Press Ctrl+C to exit
Traceback (most recent call last):
  File "c:\users\lelik\anaconda3\envs\py356\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lelik\anaconda3\envs\py356\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lelik\anaconda3\envs\py356\Scripts\rosreestr2coord.exe\__main__.py", line 7, in <module>
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\console.py", line 144, in console
    run_console(opt)
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\console.py", line 95, in run_console
    get_by_code(code, output, display=opt.display, **kwargs)
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\console.py", line 99, in get_by_code
    area = Area(code, **kwargs)
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\parser.py", line 121, in __init__
    self.workspace = self.create_workspace()
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\parser.py", line 131, in create_workspace
    area_path_name = self.clear_code(self.code).replace(':', '_')
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\parser.py", line 252, in clear_code
    return ':'.join([str(int(x)) for x in code.split(':')])
  File "c:\users\lelik\anaconda3\envs\py356\lib\site-packages\rosreestr2coord\parser.py", line 252, in <listcomp>
    return ':'.join([str(int(x)) for x in code.split(':')])
ValueError: invalid literal for int() with base 10: '00-6.744'

Судя по всему, инструменту не нравится формат Реестрового номера ЗОУИТ. Возможно ли в инструменте работать с ЗОУИТ?

**Comment by rendrom** [comment]
Было исправлено в какой-то из версий

![image](https://github.com/user-attachments/assets/90755ff1-d267-4413-befb-54298bbe76e4)
