### ISSUE TITLE
Проблема с развёртыванием

### ISSUE THREAD

**Issue by palandovalex** [rendrom/rosreestr2coord#71]
Развернул rosreestr2coord в докере, все зависимости он подтягивал сам, в том числе и opencv скомпилировал. Тестирую, и он выдаёт мне такое:

```
# rosreestr2coord -c 38:06:144003:4723
Press Ctrl+C to exit
Area info loaded from file: /app/tmp/38_6_144003_4723/feature_info.json
Get tiles:
100% 1/1
Completed, 1 tile received
raster - /app/tmp/38_6_144003_4723/1000_1000/0_0.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 125, in __init__
    self.get_geometry()
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 290, in get_geometry
    return self.parse_geometry_from_image()
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 315, in parse_geometry_from_image
    return self.get_image_geometry()
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 333, in get_image_geometry
    image_xy_corner = self.image_xy_corner = self.get_image_xy_corner()
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 344, in get_image_xy_corner
    import cv2
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/cv2/gapi/__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rosreestr2coord", line 8, in <module>
    sys.exit(console())
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/console.py", line 202, in console
    run_console(opt)
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/console.py", line 151, in run_console
    get_by_code(code, output, display=opt.display, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/console.py", line 155, in get_by_code
    area = Area(code, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rosreestr2coord/parser.py", line 129, in __init__
    if er.reason:
AttributeError: 'AttributeError' object has no attribute 'reason'

```

**Comment by palandovalex** [comment]
# cat /etc/issue
Debian GNU/Linux 10 \n \l

версии подтянутых зависимостей:

opencv-python      4.6.0.66
rosreestr2coord    4.1.6
numpy              1.23.5
Pillow             9.2.0

matplotlib - не был установлен.

**Comment by palandovalex** [comment]
Прошу прощения, я нашел эту проблему в opencv:
https://github.com/asweigart/pyautogui/issues/706
Там предлагается сделать даунрейд:
`pip install opencv-python==4.5.5.64`
Проблема в том, что ваша библиотека с этой версией CV2 не дружит.

**Comment by rendrom** [comment]
Спасибо, поправлю

**Comment by palandovalex** [comment]
День добрый. Вопрос - какая версия rosreestr2coord дружит с opencv-python==4.5.5.64?

**Comment by spiner2000** [comment]
После обновлении на 4.1.7 из-за этого даунгрейда  (opencv-python==4.5.5.64)  ломается билд opencv в среде python 3.10 При этом с 4.6.0.66  всё замечательно, так что решение весьма спорное.

**Comment by rendrom** [comment]
Сейчас 4.2.7 с opencv-contrib-python==4.5.3.56 вместо opencv-python
Тоже сталкнулся с проблемами при развертывании в докер контейнере
