### ISSUE TITLE
Ругается на 0 в кадастровом номере

### ISSUE THREAD

**Issue by samorez1** [rendrom/rosreestr2coord#83]
Здравствуйте, подскажите, пожалуйста, в чем может быть проблема?

> rosreestr2coord -c 38:06:144003:4723 -P
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\codeop.py", line 161, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\codeop.py", line 126, in __call__
    codeob = compile(source, filename, symbol, flags, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1
    rosreestr2coord -c 38:06:144003:4723 -P
                          ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

**Comment by Avantime-pro** [comment]
Здравствуйте. Попробуйте убрать ведущий ноль: rosreestr2coord -c 38:6:144003:4723 -P
