### ISSUE TITLE
Не могу запустить скрипт

### ISSUE THREAD

**Issue by vaterekhoff** [rendrom/rosreestr2coord#88]
Здравствуйте, установил скрипт через pip, python-3.12.7. при запуске выдает следующее
D:\>py -m rosreestr2coord -c 38:06:144003:4723
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\__init__.py", line 1, in <module>
    from rosreestr2coord.parser import Area
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\parser.py", line 11, in <module>
    from .merge_tiles import PkkAreaMerger
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\merge_tiles.py", line 16, in <module>
    from .request.request import make_request
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\request\request.py", line 3, in <module>
    from requests import RequestException
ModuleNotFoundError: No module named 'requests'

**Comment by vaterekhoff** [comment]
прописал в переменные среды пути (path) к каталогам  C:\Users\Vitaliy\AppData\Roaming\Python\Python312\Scripts, C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages

C:\Users\Vitaliy>rosreestr2coord -c 38:06:144003:4723
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\Scripts\rosreestr2coord.exe\__main__.py", line 4, in <module>
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\__init__.py", line 1, in <module>
    from rosreestr2coord.parser import Area
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\parser.py", line 11, in <module>
    from .merge_tiles import PkkAreaMerger
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\merge_tiles.py", line 16, in <module>
    from .request.request import make_request
  File "C:\Users\Vitaliy\AppData\Roaming\Python\Python312\site-packages\rosreestr2coord\request\request.py", line 3, in <module>
    from requests import RequestException
ModuleNotFoundError: No module named 'requests'

**Comment by rendrom** [comment]
Спасибо за отчёт об ошибке. Внёс изменения и выпустил патч 4.6.5. Обновитесь, пожалуйста до этой версии
